Repository PolkaGate/extension, pull requests merged in 2024-08, with the labels that each got.

#1215 Add Alerts
  packages/extension-polkagate/src/components/ErrorBoundary.tsx
  packages/extension-polkagate/src/components/contexts.tsx
  packages/extension-polkagate/src/fullscreen/accountDetails/components/LockedBalanceDisplay.tsx
  packages/extension-polkagate/src/fullscreen/accountDetails/index.tsx
  packages/extension-polkagate/src/fullscreen/accountDetails/unlock/Review.tsx
  packages/extension-polkagate/src/fullscreen/homeFullScreen/index.tsx
  packages/extension-polkagate/src/fullscreen/homeFullScreen/partials/ProfileTab.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/partials/Info.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/partials/Info.tsx
  packages/extension-polkagate/src/hooks/useAssetsBalances.ts
  packages/extension-polkagate/src/partials/Alert.tsx
  packages/extension-polkagate/src/partials/AlertBox.tsx
  packages/extension-polkagate/src/partials/OptionalCopyPopup.tsx
  packages/extension-polkagate/src/popup/account/unlock/LockedInReferenda.tsx
  packages/extension-polkagate/src/popup/forgetAccount/ForgetAccountModal.tsx
  packages/extension-polkagate/src/popup/home/ManageHome.tsx
  packages/extension-polkagate/src/popup/home/news.ts
  packages/extension-polkagate/src/util/types.ts
  packages/extension-ui/src/Popup/index.tsx
  packages/extension/public/locales/en/translation.json
Labels: priority, test, ready to be merged

#1471 fix ledger issue
  packages/extension-polkagate/src/hooks/useGenericLedger.ts
  packages/extension-polkagate/src/popup/signing/LedgerSignGeneric.tsx
Labels: bug, test

#1473 Fix ledger offset issue
  packages/extension-polkagate/src/components/SignWithLedger.tsx
  packages/extension-polkagate/src/popup/home/news.ts
  packages/extension-polkagate/src/popup/import/importLedger/GenericApp.tsx
  packages/extension-polkagate/src/popup/import/importLedger/ManualLedgerImport.tsx
  packages/extension-polkagate/src/popup/signing/LedgerSignGeneric.tsx
  packages/extension-polkagate/src/popup/signing/Request/index.tsx
Labels: bug, priority

#1078 Transferable vs available balance! address #1071
  packages/extension-polkagate/src/fullscreen/accountDetails/components/LockedInReferendaFS.tsx
  packages/extension-polkagate/src/fullscreen/accountDetails/components/index.ts
  packages/extension-polkagate/src/fullscreen/accountDetails/index.tsx
  packages/extension-polkagate/src/fullscreen/governance/post/decisionDeposit/index.tsx
  packages/extension-polkagate/src/fullscreen/sendFund/InputPage.tsx
  packages/extension-polkagate/src/hooks/index.ts
  packages/extension-polkagate/src/hooks/useAssetsBalances.ts
  packages/extension-polkagate/src/hooks/useBalances.ts
  packages/extension-polkagate/src/hooks/useTimeToUnlock.tsx
  packages/extension-polkagate/src/popup/account/Others.tsx
  packages/extension-polkagate/src/popup/account/index.tsx
  packages/extension-polkagate/src/popup/account/unlock/LockedInReferenda.tsx
  packages/extension-polkagate/src/popup/account/util.ts
  packages/extension-polkagate/src/popup/crowdloans/contribute/Contribute.tsx
  packages/extension-polkagate/src/popup/send/index.tsx
  packages/extension-polkagate/src/popup/staking/pool/stake/StakeInitialChoice.tsx
  packages/extension-polkagate/src/popup/staking/pool/stake/bondExtra/index.tsx
  packages/extension-polkagate/src/popup/staking/solo/index.tsx
  packages/extension-polkagate/src/util/types.ts
  packages/extension-polkagate/src/util/workers/getAssetOnAssetHub.js
  packages/extension-polkagate/src/util/workers/getAssetOnRelayChain.js
  packages/extension-polkagate/src/util/workers/utils/balancify.js
  packages/extension-polkagate/src/util/workers/utils/toGetNativeToken.js
Labels: priority

#1501 fix where some chains such as Parallel does not support api.query['system']['account']
  packages/extension-polkagate/src/hooks/useBalances.ts
Labels: bug, priority

#1505 refactor and put StakingInput type in a new file
  packages/extension-polkagate/src/components/AccountHolder.tsx
  packages/extension-polkagate/src/components/AccountHolderWithProxy.tsx
  packages/extension-polkagate/src/components/SignArea2.tsx
  packages/extension-polkagate/src/fullscreen/stake/Entry.tsx
  packages/extension-polkagate/src/fullscreen/stake/easyMode/Review.tsx
  packages/extension-polkagate/src/fullscreen/stake/easyMode/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/partials/Review.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/commonTasks/SetState.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/commonTasks/editPool/Review.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/commonTasks/editPool/ShowPoolRole.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/commonTasks/leavePool/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/commonTasks/manageValidators/InputPage.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/commonTasks/manageValidators/Review.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/commonTasks/manageValidators/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/commonTasks/removeAll/Review.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/create/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/join/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/redeem/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/rewards/stake/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/rewards/withdraw/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/stake/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/pool/unstake/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/commonTasks/configurePayee/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/commonTasks/manageValidators/InputPage.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/commonTasks/manageValidators/Review.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/commonTasks/manageValidators/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/fastUnstake/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/partials/SelectValidators.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/partials/ShowValidator.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/partials/ValidatorsTableFS.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/pending/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/redeem/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/restake/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/stake/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/stakeExtra/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/unstake/index.tsx
  packages/extension-polkagate/src/fullscreen/stake/type.ts
  packages/extension-polkagate/src/hooks/useEstimatedFee.ts
  packages/extension-polkagate/src/hooks/usePoolConsts.ts
  packages/extension-polkagate/src/hooks/useStakingConsts.ts
  packages/extension-polkagate/src/popup/staking/partial/SelectValidatorsReview.tsx
  packages/extension-polkagate/src/popup/staking/partial/ShowPool.tsx
  packages/extension-polkagate/src/util/types.ts
  packages/extension-ui/src/createView.tsx
Labels: priority

#1508 notify users on chain changes
  packages/extension-polkagate/src/fullscreen/accountDetails/components/AOC.tsx
  packages/extension-polkagate/src/fullscreen/accountDetails/components/AccountInformationForDetails.tsx
  packages/extension-polkagate/src/fullscreen/homeFullScreen/partials/AccountInformationForHome.tsx
  packages/extension-polkagate/src/hooks/index.ts
  packages/extension-polkagate/src/hooks/useAccount.ts
  packages/extension-polkagate/src/hooks/useInfo.ts
  packages/extension-polkagate/src/hooks/useNotifyOnChainChange.ts
  packages/extension-polkagate/src/partials/AlertBox.tsx
  packages/extension/public/locales/en/translation.json
Labels: enhancement

#1515 refactor and replace advance settings with rewards destination
  packages/extension-base/src/background/handlers/index.ts
  packages/extension-polkagate/src/fullscreen/stake/pool/commonTasks/manageValidators/InputPage.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/commonTasks/manageValidators/InputPage.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/partials/SelectValidatorsFs.tsx
  packages/extension-polkagate/src/fullscreen/stake/solo/stake/index.tsx
  packages/extension-polkagate/src/hooks/useValidators.ts
  packages/extension-polkagate/src/popup/staking/partial/SelectValidators.tsx
  packages/extension-polkagate/src/popup/staking/partial/SelectValidatorsReview.tsx
  packages/extension-polkagate/src/popup/staking/pool/nominations/index.tsx
  packages/extension-polkagate/src/popup/staking/pool/nominations/remove/index.tsx
  packages/extension-polkagate/src/popup/staking/solo/fastUnstake/index.tsx
  packages/extension-polkagate/src/popup/staking/solo/nominations/index.tsx
  packages/extension-polkagate/src/popup/staking/solo/nominations/remove/index.tsx
  packages/extension-polkagate/src/popup/staking/solo/stake/index.tsx
  packages/extension-polkagate/src/popup/staking/solo/stake/partials/SetPayeeController.tsx
  packages/extension-polkagate/src/popup/staking/solo/stake/partials/SettingsHeader.tsx
  packages/extension-polkagate/src/util/types.ts
  packages/extension/public/locales/en/translation.json
  packages/extension/src/background.ts
Labels: priority
